FROM alpine:3.15.0
LABEL version "1.0.0" maintainer="Yazid Brakni" os="ubuntu" distro="stro"
ENV CONTAINER_USER "Yazid_Brakni"
RUN adduser -S -D $CONTAINER_USER
CMD ["echo", "hello-alpine, my name is Yazid Brakni and this is a container from my first image"]
