FROM alpine:3.15.0
LABEL version="1.0.0"
MAINTAINER="Yazid Brakni"
os="ubuntu"
ENV Container_user="Yazid_Brakni"
RUN adduser --disabled-password Yazid_Brakni
CMD ["echo", "hello-alpine, I’m Yazid Brakni  and this is a container from my first image"]
