FROM Alpine 3.15.0
LABEL version "1.0.0" maintainers="Yazid Brakni" os="unbuntu"
ENV Container_user="Yazid Brakni"
RUN adduser --disabled-password Yazid_Brakni
CMD ["echo", "hello-alpine, my name is Yazid Brakni and this is a container from my first image"]
